# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
jobs:
  make:
    docker:
      - image: cimg/base:2020.12
    steps:
      - checkout
      - run:
          name: make
          command: ls -l && uname -a && make ARM64 && ./crash --help
      - run:
          name: move to artifacts
          command: mkdir artifacts && mv crash ./artifacts/
workflows:
  # Name the workflow "build"
  build:
    # Run the build/run job in its own container
    jobs:
      - welcome/run
      - make
