name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make ARM64
      run: make target=ARM64 && ls -l && ./crash
    - name: get crash tool ARM64
      uses: actions/upload-artifact@v2
      with:
        name: crashtool_ARM64
        path: crash
    - name: clean
      run: make clean
    - name: make X86_64
      run: make target=X86_64 && ls -l && ./crash
    - name: get crash tool X86_64
      uses: actions/upload-artifact@v2
      with:
        name: crashtool_X86_64
        path: crash
        
